name: Prod release

on:
  workflow_run:
    workflows: [Release new version]
    types:
      - completed

env:
  GHCR_REGISTRY: ghcr.io
  GHCR_IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/wavv-backend      

permissions:
  contents: read
  packages: write

jobs:
  Deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 21
        uses: actions/setup-node@v1
        with:
          node-version: 21.X

      - name: Set current release version
        id: get-version
        run: |
          VERSION=$(GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} gh release view --json tagName --jq .tagName)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          file: Dockerfile
          tags: |
            ${{ env.GHCR_IMAGE_NAME }}:${{ steps.get-version.outputs.version }}
            ${{ env.GHCR_IMAGE_NAME }}:${{ github.sha }}

      - name: Set up the app prod specs
        run: |
          mkdir -p .do
          GITHUB_TOKEN=${{ secrets.WAVV_REPO_PERSONAL_ACCESS_TOKEN }} gh api repos/${{ github.repository_owner }}/wavv-infrastructure/contents/.do/app.prod.yaml \
            --header "Accept: application/vnd.github.v3.raw" > .do/app.prod.yaml

      - name: Deploy the wavv-prod-backend app
        uses: digitalocean/app_action/deploy@v2
        env:
          SAMPLE_DIGEST: ${{ steps.push.outputs.digest }}
        with:
            token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
            app_spec_location: .do/app.prod.yaml
