name: Production release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.X

      - name: Install Railway
        run: npm i -g pnpm

      - name: Install packages
        run: pnpm install

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Production
        run: railway up --service a878b9d9-e826-4089-a688-577441eb2f2c
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}
