name: Deploy to production

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.X

      - name: Install packages
        run: pnpm install

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy to Production
        run: railway up --service 462a305d-1d04-41cb-bf0a-6a200fa0ed7f
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PRODUCTION_TOKEN }}
