name: Linting

on:
  push:
    branches:
      - main
    
permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.1.x

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint
