name: Publish

on:
  push:
    branches:
      - main
env:
  GHCR_REGISTRY: ghcr.io
  GHCR_IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node 20
        uses: actions/setup-node@v1
        with:
          node-version: 20.X
      - name: Login into GitHub Container regestry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            platforms: linux/amd64
            tags: ${{ github.sha }}
            file: Dockerfile
            
